#!/bin/bash
trashDir=~/.trash
trashLog=~/.trash.log
fileName=$PWD/$1
if [[ $# -ne 1 ]]
then
	echo "Bad argument"
	exit 1
fi

if [[ ! -f "$fileName" ]]
then
	echo "File not found"
	exit 1
fi

if [[ "$0" == "./$1" ]]
then
	echo "Can't delet this script file"
	exit 1
fi

if [[ ! -d "$trashDir" ]]
then
	mkdir "$trashDir"
fi

if [[ ! -f "$trashLog" ]]
then
	touch "$trashLog"
fi

linkName=$(cat "$trashLog" | wc -l)
ln "$fileName" "$trashDir/$linkName"
rm "$fileName"

echo "$fileName:$linkName">> "$trashLog"
