#!/bin/bash
restorDir="/home/kules/restore"
userDir="/home/kules"
dateReg="[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}"
dateRegEnd="[0-9]{4}-[0-9]{2}-[0-9]{2}$"
if [[ ! -d $restorDir ]]
then
	mkdir $restorDir
fi
lastBackup=$(ls $userDir | grep -e "Backup-$dateReg" | sort -n | tail -n 1)
if [[ -z $lastBackup ]]
then
	echo "Backup not found"
	exit
fi
backupDir="$userDir/$lastBackup"
for nowFile in $(ls $backupDir)
do
	if [[ ! "$nowFile" =~ $dateRegEnd ]]
	then
		cp -r "$backupDir/$nowFile" "$restorDir"
	fi
done
