#!/bin/bash
nowDate=$(date +"%F")
sourceDir="/home/kules/source"
backupRepotFile="/home/kules/backup-report"
userDir="/home/kules"
lastBackup=$(ls $userDir | grep -e "Backup-[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}" | sort -n | tail -n 1)
backupDir=""
if [[ -z $lastBackup ]]
then
	backupDir="Backup-$nowDate"
else
	dateLastBackup="$(echo $lastBackup | awk -F "-" '{print $2"-"$3"-"$4}')"
	sub="$(( $(date -d $nowDate +"%s") - $(date -d $dateLastBackup +"%s")))"
	let sub=sub/60/60/24
	if [[ $sub -lt 7 ]]
	then
		backupDir=$lastBackup
	else
		backupDir="Backup-$nowDate"
	fi
fi
fullNameBackupDir="$userDir/$backupDir"
if [[ ! -d "$fullNameBackupDir" ]]
then
	mkdir "$fullNameBackupDir"
	cp -a -T "$sourceDir" "$fullNameBackupDir"
	echo "Backup $backupDir was created on $nowDate">>"$backupRepotFile"
	echo $(ls "$sourceDir")>>"$backupRepotFile"
else
	renamed=""
	copied=""
	for nowFile in $(ls "$sourceDir")
	do
		if [[ -f "$fullNameBackupDir/$nowFile" ]]
		then
			fileSource="$sourceDir/$nowFile"
			fileBackup="$fullNameBackupDir/$nowFile"
			sizeBackup=$(wc -c "$fileBackup" | awk '{print $1}')
			sizeSource=$(wc -c "$fileSource" | awk '{print $1}')
			if [[ $sizeBackup -ne $sizeSource ]]
			then
				mv $fileBackup $fileBackup.$nowDate
				cp -r "$fileSource" "$fullNameBackupDir"
				renamed="$renamed$fileBackup $fileBackup.$nowDate\n"
			fi
		else
			cp -r "$sourceDir/$nowFile" "$fullNameBackupDir"
			copied="$copied$nowFile\n"
		fi
	done
	echo $backupDir was changed on $nowDate>>$backupRepotFile
	echo -e $copied>>"$backupRepotFile"
	echo -e $renamed>>"$backupRepotFile"
fi
